### ISSUE TITLE
Integration of a video in our website.

### ISSUE THREAD

**Issue by preyashyadav** [Gitit-hacktoberfest/GitInto-Website#10]
Recently we hosted an event named Hackoween, for this event we developed a website: https://gitinto.netlify.app/
Since the event is over now, we want to add the video recording of this event on our website. If you think you can contribute by doing this part, you are most welcome. If you are interested reply to this, we'll discuss further details with you.

**Comment by attreyee-muk** [comment]
Can I contribute to this? Pls assign it to me.

**Comment by preyashyadav** [comment]
Hey there! Thanks for taking the initiative. I'll quickly explain what exactly we want.

![image](https://user-images.githubusercontent.com/73031725/137896302-6d1f5dd5-9862-40e8-af20-32d451b03b3e.png)

We want you to make changes in this div, since the event is over you can replace the heading "Register for the event" with "Introduction to open source" and then add the video just below this heading (It can be a thumbnail of the video or muted video itself).

Somewhat like this:

![image](https://user-images.githubusercontent.com/73031725/137897469-9e4ec159-4c63-44cb-97f0-72a0e14ce15e.png)

You can rename the button from "Register" to "Watch video" 

Here's the link of the video : https://drive.google.com/file/d/1Cg1NClz4k4DBUPPVobRzEm6JAHPGjwiu/view?usp=sharing
Also please take care about the responsiveness of the website. Feel free to ask your doubts(if you have any).😊

**Comment by attreyee-muk** [comment]
Can you pls provide the YouTube link for the same video?

**Comment by preyashyadav** [comment]
Yea sure.

https://youtu.be/JehEfea4dZY

**Comment by attreyee-muk** [comment]
I made the required changes, but the Hacktoberfest website says that your project is not participating.

**Comment by preyashyadav** [comment]
Yea actually it won't show up untill we add the "hacktoberfest accepted" label to it.

**Comment by attreyee-muk** [comment]
Hello! I made the required changes for the mobile viewing. Pls see it and if there is any problem, do let me know. thank you!
