### ISSUE TITLE
Center Register button

### ISSUE THREAD

**Issue by PranavViswanathan** [Gitit-hacktoberfest/GitInto-Website#6]
On the website, there is a register button, it is not exactly centered in the div.  It needs to be fixed.
Pull requests are welcome.

# Contributing standards:

Ensure that the  changes you are making are pushed to a patchfix-1 and not made on the main branch

**Comment by ToluAdegboyega** [comment]
Hello! Can I be assigned this?

**Comment by PranavViswanathan** [comment]
Thank you @ToluAdegboyega!
Issue fixed by @ToluAdegboyega (PR #7 ). 
Closing issue.
